Grain.create(name:'Acid Malt', grain_type: 'Grain', extract_potential: 1.027)
Grain.create(name:'Amber Malt', grain_type: 'Grain', extract_potential: 1.035)
Grain.create(name:'Aromatic Malt', grain_type: 'Grain', extract_potential: 1.036)
Grain.create(name:'Biscuit Malt', grain_type: 'Grain', extract_potential: 1.036)
Grain.create(name:'Black (Patent) Malt', grain_type: 'Grain', extract_potential: 1.025)
Grain.create(name:'Brown Malt', grain_type:'Grain', extract_potential: 1.032)
Grain.create(name:'Cara-Pils/Dextrine', grain_type: 'Grain', extract_potential: 1.033)
Grain.create(name:'Caramel/Crystal Malt – 10L', grain_type: 'Grain', extract_potential: 1.035)
Grain.create(name:'Caramel/Crystal Malt – 20L', grain_type: 'Grain', extract_potential: 1.035)
Grain.create(name:'Caramel/Crystal Malt – 30L', grain_type: 'Grain', extract_potential: 1.035)
Grain.create(name:'Caramel/Crystal Malt – 40L', grain_type: 'Grain', extract_potential: 1.034)
Grain.create(name:'Caramel/Crystal Malt – 60L', grain_type: 'Grain', extract_potential: 1.034)
Grain.create(name:'Caramel/Crystal Malt – 80L', grain_type: 'Grain', extract_potential: 1.034)
Grain.create(name:'Caramel/Crystal Malt -120L', grain_type: 'Grain', extract_potential: 1.033)
Grain.create(name:'Chocolate Malt', grain_type: 'Grain', extract_potential: 1.028)
Grain.create(name:'Melanoiden Malt', grain_type: 'Grain', extract_potential: 1.037 )
Grain.create(name:'Munich Malt – 10L', grain_type: 'Grain', extract_potential: 1.035 )
Grain.create(name:'Munich Malt – 20L', grain_type: 'Grain', extract_potential: 1.035 )
Grain.create(name:'Pale Malt (6 Row)', grain_type: 'Grain', extract_potential: 1.035)
Grain.create(name:'Pilsner (2 Row)', grain_type: 'Grain', extract_potential: 1.036)
Grain.create(name:'Smoked Malt', grain_type: 'Grain', extract_potential: 1.037)
Grain.create(name:'Special Roast', grain_type: 'Grain', extract_potential: 1.033)
Grain.create(name:'Toasted Malt', grain_type: 'Grain', extract_potential: 1.033)
Grain.create(name:'Victory Malt', grain_type: 'Grain', extract_potential: 1.034)
Grain.create(name:'Vienna Malt', grain_type: 'Grain', extract_potential: 1.036)


#Extract
Grain.create(name:'Extra Light Dry', grain_type: 'Extract', extract_potential:1.044)
Grain.create(name:'Dark Liquid ', grain_type: 'Extract' , extract_potential: 1.036)
Grain.create(name:'Dark Dry', grain_type: 'Extract', extract_potential:1.044)
Grain.create(name:'Amber Dry ', grain_type: 'Extract', extract_potential:  1.044)
Grain.create(name:'Amber Liquid', grain_type: 'Extract', extract_potential: 1.036)
Grain.create(name:'Light Dry', grain_type: 'Extract', extract_potential:1.044)
Grain.create(name:'Pale Liquid ', grain_type: 'Extract', extract_potential:1.036)
Grain.create(name:'Pilsner Liquid', grain_type: 'Extract', extract_potential:1.036)
Grain.create(name:'Rice Extract Syrup', grain_type: 'Extract', extract_potential:1.032)
Grain.create(name:'Wheat Dry', grain_type: 'Extract', extract_potential:1.044)
Grain.create(name:'Wheat Liquid', grain_type: 'Extract', extract_potential:1.036)


#Adjunct
Grain.create(name:'Barley Hulls', grain_type:'Adjunct', extract_potential: 1.000)
Grain.create(name:'Barley, Flaked', grain_type:'Adjunct', extract_potential:1.032)
Grain.create(name:'Barley, Raw', grain_type:'Adjunct', extract_potential:1.028)
Grain.create(name:'Barley, Torrefied', grain_type:'Adjunct', extract_potential:1.036)
Grain.create(name:'Corn, Flaked', grain_type:'Adjunct', extract_potential: 1.037)
Grain.create(name:'Grits', grain_type:'Adjunct', extract_potential:1.037)
Grain.create(name:'Oats, Flaked', grain_type:'Adjunct', extract_potential:1.037)
Grain.create(name:'Oats, Malted', grain_type:'Adjunct', extract_potential:1.037)
Grain.create(name:'Rice Hulls', grain_type:'Adjunct', extract_potential: 1.000)
Grain.create(name:'Rice, Flaked', grain_type:'Adjunct', extract_potential:1.032)
Grain.create(name:'Roasted Barley', grain_type:'Adjunct', extract_potential:1.025)
Grain.create(name:'Rye Malt', grain_type: 'Adjunct', extract_potential:1.029)
Grain.create(name:'Rye, Flaked', grain_type:'Adjunct', extract_potential:1.036)
Grain.create(name:'Black Barley (Stout)', grain_type: 'Adjunct', extract_potential: 1.025)
Grain.create(name:'Wheat Malt', grain_type: 'Grain', extract_potential:1.037)
Grain.create(name:'Wheat Malt, Dark', grain_type: 'Grain', extract_potential:1.039)
Grain.create(name:'Wheat, Flaked', grain_type: 'Grain', extract_potential:1.035)
Grain.create(name:'Wheat, Roasted', grain_type:'Grain', extract_potential:1.025)
Grain.create(name:'Wheat, Torrified', grain_type: 'Grain', extract_potential:1.036)
Grain.create(name:'White Wheat Malt', grain_type: 'Grain', extract_potential:1.040)

#Sugar
Grain.create(name:'Brown Sugar, Dark', grain_type:'Sugar', extract_potential:1.046)
Grain.create(name:'Brown Sugar, Light', grain_type:'Sugar', extract_potential:1.046)
Grain.create(name:'Candi Sugar, Amber', grain_type: 'Sugar', extract_potential:1.036)
Grain.create(name:'Candi Sugar, Clear', grain_type:'Sugar', extract_potential:1.036)
Grain.create(name:'Candi Sugar, Dark', grain_type:'Sugar', extract_potential:1.036)
Grain.create(name:'Cane (Beet) Sugar', grain_type:'Sugar', extract_potential:1.046)
Grain.create(name:'Corn Syrup', grain_type:'Sugar', extract_potential:1.036)
Grain.create(name:'Corn Sugar (Dextrose)', grain_type:'Sugar', extract_potential:1.046)
Grain.create(name:'Dememera Sugar', grain_type:'Sugar', extract_potential:1.046)
Grain.create(name:'Honey', grain_type:'Extract', extract_potential: 1.035)
Grain.create(name:'Invert Sugar', grain_type:'Sugar', extract_potential:1.046)
Grain.create(name:'Maple Syrup', grain_type:'Sugar', extract_potential:1.030)
Grain.create(name:'Milk Sugar (Lactose)', grain_type:'Sugar', extract_potential:1.035)
Grain.create(name:'Molasses', grain_type:'Sugar', extract_potential:1.036)
Grain.create(name:'Sugar, Table (Sucrose)', grain_type:'Sugar', extract_potential:1.046)
Grain.create(name:'Turbinado', grain_type:'Sugar', extract_potential:1.044)

#hops
Hop.create(name:'Amarillo', origin: 'U.S.', alpha_acid: 9)
Hop.create(name: 'Apollo', origin: 'U.S.', alpha_acid: 20.5)
Hop.create(name: "Brewer's Gold", origin: 'England', alpha_acid: 9.2)
Hop.create(name: 'Cascade', origin: 'U.S.', alpha_acid: 5.4)
Hop.create(name: 'Centennial', origin: 'U.S.', alpha_acid: 10.5)
Hop.create(name: 'Challenger', origin: 'England',  alpha_acid: 7.5)
Hop.create(name: 'Chinook', origin: 'U.S.', alpha_acid: 13)
Hop.create(name: 'Citra®', origin: 'U.S.', alpha_acid: 12)
Hop.create(name: 'Cluster', origin: 'U.S.', alpha_acid: 6.75)
Hop.create(name: 'Columbus', origin: 'U.S.', alpha_acid: 16)
Hop.create(name: 'Crystal', origin: 'U.S.', alpha_acid: 4.5)
Hop.create(name: 'Eroica', origin: 'U.S.', alpha_acid: 10.5)
Hop.create(name: 'Fuggle', origin: 'England',  alpha_acid: 4.75)
Hop.create(name: 'Galaxy', origin: 'Australia', alpha_acid: 14.9)
Hop.create(name: 'Galena', origin: 'U.S.', alpha_acid: 13)
Hop.create(name: 'Goldings ', origin: 'England',  alpha_acid: 4.75)
Hop.create(name: 'Hallertau / Hallertauer Mittelfrüh', origin: 'Germany', alpha_acid: 4.5)
Hop.create(name: 'Hersbrucker', origin: 'Germany', alpha_acid: 4.25)
Hop.create(name: 'Liberty', origin: 'U.S.', alpha_acid: 4)
Hop.create(name: 'Magnum', origin: 'Germany', alpha_acid: 1.3)
Hop.create(name: 'Mosaic', origin: 'U.S.', alpha_acid: 12.5)
Hop.create(name: 'Mount Hood', origin: 'U.S.', alpha_acid: 6.5)
Hop.create(name: 'Northern Brewer', origin: 'England', alpha_acid: 9)
Hop.create(name: 'Nugget', origin: 'U.S.', alpha_acid: 13)
Hop.create(name: 'Palisade', origin: 'U.S.', alpha_acid: 8)
Hop.create(name: 'Perle', origin: 'Germany', alpha_acid: 8)
Hop.create(name: 'Pride of Ringwood', origin: 'Australia', alpha_acid: 8.75)
Hop.create(name: 'Saaz', origin: 'Czech Republic', alpha_acid: 3.75)
Hop.create(name: 'Rubin', origin: 'Czech Republic', alpha_acid: 10.5)
Hop.create(name: 'Bohemie', origin: 'Czech Republic', alpha_acid: 6.75)
Hop.create(name: 'Saphir', origin: 'Germany', alpha_acid: 3.25)
Hop.create(name: 'Select', origin: 'Germany', alpha_acid: 5)
Hop.create(name: 'Simcoe', origin: 'U.S.', alpha_acid: 13)
Hop.create(name: 'Sorachi Ace', origin: 'Japan', alpha_acid: 13)
Hop.create(name: 'Southern Cross', origin: 'New Zealand', alpha_acid: 12.75)
Hop.create(name: 'Spalt', origin: 'Germany', alpha_acid: 4.5)
Hop.create(name: 'Sterling', origin: 'U.S.', alpha_acid: 7.75)
Hop.create(name: 'Styrian Aurora', origin: 'Slovenia', alpha_acid: 8.25)
Hop.create(name: 'Styrian Bobek', origin: 'Slovenia', alpha_acid: 5.5)
Hop.create(name: 'Styrian Goldings', origin: 'Slovenia', alpha_acid: 5.25)
Hop.create(name: 'Styrian Celeia', origin: 'Slovenia', alpha_acid: 4.5)
Hop.create(name: 'Summit', origin: 'U.S.', alpha_acid: 18)
Hop.create(name: 'Tettnang', origin: 'Germany', alpha_acid: 4.5)
Hop.create(name: 'Tradition', origin: 'Germany', alpha_acid: 6)
Hop.create(name: 'Ultra', origin: 'U.S.', alpha_acid: 4.75)
Hop.create(name: 'Zeus', origin: 'U.S.', alpha_acid: 15)

#Wheat
Yeast.create(name:'Bavarian Weizen WLP351', yeast_type: 'Wheat', attenuation: 75)
Yeast.create(name:'Hefeweizen Ale WLP300', yeast_type: 'Wheat', attenuation: 74)
Yeast.create(name:'American Whea WY1010', yeast_type: 'Wheat', attenuation: 76)
Yeast.create(name:'Bavarian Wheat WY3056', yeast_type: 'Wheat', attenuation: 75)
Yeast.create(name:'Bavarian Wheat WY3638', yeast_type: 'Wheat', attenuation: 73)
Yeast.create(name:'Belgian Wheat WY3942', yeast_type: 'Wheat', attenuation: 74)
Yeast.create(name:'German Wheat WY3333', yeast_type: 'Wheat', attenuation: 73)
Yeast.create(name:'Weihenstephan Weizen WY3068', yeast_type: 'Wheat', attenuation: 75)

#lager
Yeast.create(name:'American Lager WLP840', yeast_type: 'Lager', attenuation: 77.5)
Yeast.create(name:'Czech Budejovice Lager WLP802', yeast_type: 'Lager', attenuation: 77.5)
Yeast.create(name:'German Bock Lager WLP833', yeast_type: 'Lager', attenuation: 73)
Yeast.create(name:'German Lager WLP830', yeast_type: 'Lager', attenuation: 76.5)
Yeast.create(name:'Mexican Lager WLP940', yeast_type: 'Lager', attenuation: 74)
Yeast.create(name:'Oktoberfest/Märzen Lager WLP820', yeast_type: 'Lager', attenuation: 69)
Yeast.create(name:'Pilsner Lager WLP800', yeast_type: 'Lager', attenuation: 74.5)
Yeast.create(name:'San Francisco Lager WLP810', yeast_type: 'Lager', attenuation: 67.5)
Yeast.create(name:'Southern German Lager WLP838', yeast_type: 'Lager', attenuation: 72)
Yeast.create(name:'Zurich Lager WLP885', yeast_type: 'Lager', attenuation: 75)
Yeast.create(name:'American Lager WY2035', yeast_type: 'Lager', attenuation: 75)
Yeast.create(name:'Bavarian Lager WY2206', yeast_type: 'Lager', attenuation: 75)
Yeast.create(name:'Bohemian Lager WY2124', yeast_type: 'Lager', attenuation: 75)
Yeast.create(name:'Budvar Lager WY2000', yeast_type: 'Lager', attenuation: 73)
Yeast.create(name:'California Lager WY2112', yeast_type: 'Lager', attenuation: 69)
Yeast.create(name:'Czech Pils WY2278', yeast_type: 'Lager', attenuation: 72)
Yeast.create(name:'Danish Lager WY2042', yeast_type: 'Lager', attenuation: 75)
Yeast.create(name:'Munich Lager WY2308', yeast_type: 'Lager', attenuation: 72)
Yeast.create(name:'Octoberfest Lager Blend WY2633', yeast_type: 'Lager', attenuation: 75)
Yeast.create(name:'Pilsen Lager WY2007', yeast_type: 'Lager', attenuation: 73)
Yeast.create(name:'Urquell Lager WY2001', yeast_type: 'Lager', attenuation: 74)
Yeast.create(name:'Belgian Lager WLP815', yeast_type: 'Lager', attenuation: 75)
Yeast.create(name:'Old Bavarian Lager WLP920', yeast_type: 'Lager', attenuation: 69.5)
Yeast.create(name:'North American Lager WY2272', yeast_type: 'Lager', attenuation: 73)
Yeast.create(name:'Staro Prague Lager WY2782', yeast_type: 'Lager', attenuation: 72)
Yeast.create(name:'German Lager X WLP835', yeast_type: 'Lager', attenuation: 73)
Yeast.create(name:'Copenhagen Lager WLP850', yeast_type: 'Lager', attenuation: 75)
Yeast.create(name:'Munich Helles WLP860', yeast_type: 'Lager', attenuation: 70)
Yeast.create(name:'HP Lager WLP925', yeast_type: 'Lager', attenuation: 77.5)
Yeast.create(name:'European Lager WY2247', yeast_type: 'Lager', attenuation: 75)
Yeast.create(name:'Rasenmäher Lager WY2252', yeast_type: 'Lager', attenuation: 75)
Yeast.create(name:'Rocky Mountain Lager WY2105', yeast_type: 'Lager', attenuation: 72)

#ale
Yeast.create(name:'Abbey Ale WLP530', yeast_type: 'Ale', attenuation: 77.5)
Yeast.create(name:'Antwerp Ale WLP515', yeast_type: 'Ale', attenuation: 76.5)
Yeast.create(name:'Australian Ale WLP009', yeast_type: 'Ale', attenuation: 72.5)
Yeast.create(name:'Bedford British WLP006', yeast_type: 'Ale', attenuation: 76)
Yeast.create(name:'Burton Ale WLP023', yeast_type: 'Ale', attenuation: 72)
Yeast.create(name:'California Ale WLP001', yeast_type: 'Ale', attenuation: 76.5)
Yeast.create(name:'Cream Ale Blend WLP080', yeast_type: 'Ale', attenuation: 77.5)
Yeast.create(name:'Cry Havoc WLP862', yeast_type: 'Ale', attenuation: 68)
Yeast.create(name:'Dry English Ale WLP007', yeast_type: 'Ale', attenuation: 75)
Yeast.create(name:'Dusseldorf Alt WLP036', yeast_type: 'Ale', attenuation: 68.5)
Yeast.create(name:'East Coast Ale WLP008', yeast_type: 'Ale', attenuation: 72.5)
Yeast.create(name:'Edinburgh Scottish Ale WLP028', yeast_type: 'Ale', attenuation: 72.5)
Yeast.create(name:'English Ale WLP002', yeast_type: 'Ale', attenuation: 66.5)
Yeast.create(name:'Essex Ale WLP022', yeast_type: 'Ale', attenuation: 73.5)
Yeast.create(name:'European Ale WLP011', yeast_type: 'Ale', attenuation: 67.5)
Yeast.create(name:'French Ale WLP072', yeast_type: 'Ale', attenuation: 71.5)
Yeast.create(name:'London Ale WLP013', yeast_type: 'Ale', attenuation: 71, attenuation: 71)
Yeast.create(name:'East Midlands Ale WLP039', yeast_type: 'Ale', attenuation: 77.5)
Yeast.create(name:'Pacific Ale WLP041', yeast_type: 'Ale', attenuation: 67.5)
Yeast.create(name:'Super Gravity Ale WLP099', yeast_type: 'Ale', attenuation: 85)
Yeast.create(name:'American Ale WY1056', yeast_type: 'Ale', attenuation: 75)
Yeast.create(name:'British Ale WY1098', yeast_type: 'Ale', attenuation: 74)
Yeast.create(name:'German Ale WY1007', yeast_type: 'Ale', attenuation: 75)
Yeast.create(name:'Irish Ale WY1084', yeast_type: 'Ale', attenuation: 73)
Yeast.create(name:'Kölsch WY2565', yeast_type: 'Ale', attenuation: 75)
Yeast.create(name:'London ESB Ale WY1968', yeast_type: 'Ale', attenuation: 69)
Yeast.create(name:'Northwest Ale WY1332', yeast_type: 'Ale', attenuation: 69)
Yeast.create(name:'Scottish Ale WY1728', yeast_type: 'Ale', attenuation: 71)
Yeast.create(name:'Thames Valley Ale WY1275', yeast_type: 'Ale', attenuation: 77)
Yeast.create(name:'Whitbread Ale WY1099', yeast_type: 'Ale', attenuation: 70)
Yeast.create(name:'Yorkshire Square Ale WLP037', yeast_type: 'Ale', attenuation: 70)
Yeast.create(name:'Manchester Ale WLP038', yeast_type: 'Ale', attenuation: 72)
Yeast.create(name:'San Diego Super WLP090', yeast_type: 'Ale', attenuation: 79.5)
Yeast.create(name:'American Farmhouse Blend WLP670', yeast_type: 'Ale', attenuation: 78.5)
Yeast.create(name:'French Saison WY3711', yeast_type: 'Ale', attenuation: 80)
Yeast.create(name:"Roeselare Ale Blend WY3763", yeast_type: 'Ale', attenuation: 80)
Yeast.create(name:'Farmhouse Ale WY3726', yeast_type: 'Ale', attenuation: 76)
Yeast.create(name:'English Special Bitter WY1768', yeast_type: 'Ale', attenuation: 70)
Yeast.create(name:'Leuven Pale Ale WY3538', yeast_type: 'Ale', attenuation: 76)
Yeast.create(name:'West Yorkshire WY1469', yeast_type: 'Ale', attenuation: 69)
Yeast.create(name:'Whitbread Ale WLP017', yeast_type: 'Ale', attenuation: 70)
Yeast.create(name:'Premium Bitter Ale WLP026', yeast_type: 'Ale', attenuation: 72.5)

#belgian
Yeast.create(name:'Belgian Dark Ale WY3822', yeast_type: 'Belgian Ale', attenuation: 76)
Yeast.create(name:'Belgian Stout WY1581', yeast_type: 'Belgian Ale', attenuation: 80)
Yeast.create(name:'Belgian Ale WY1214', yeast_type: 'Belgian Ale', attenuation: 75)
Yeast.create(name:'Belgian Ardennes WY3522', yeast_type: 'Belgian Ale', attenuation: 74)
Yeast.create(name:'Belgian Saison WY3724', yeast_type: 'Belgian Ale', attenuation: 78)
Yeast.create(name:'Belgian Strong Ale WY1388', yeast_type: 'Belgian Ale', attenuation: 76)
Yeast.create(name:'Belgian Witbier WY3944', yeast_type: 'Belgian Ale', attenuation: 74)
Yeast.create(name:'Belgian Ale WLP550', yeast_type: 'Belgian Ale', attenuation: 81.5)
Yeast.create(name:'Belgian Bastogne Ale WLP510', yeast_type: 'Belgian Ale', attenuation: 77)
Yeast.create(name:'Belgian Golden Ale WLP570', yeast_type: 'Belgian Ale', attenuation: 75.5)
Yeast.create(name:'Belgian Saison I WLP565', yeast_type: 'Belgian Ale', attenuation: 70)
Yeast.create(name:'Belgian Style Ale  Blend WLP575', yeast_type: 'Belgian Ale', attenuation: 77)
Yeast.create(name:'Belgian Style Saison Blend WLP568', yeast_type: 'Belgian Ale', attenuation: 75)
Yeast.create(name:'Belgian Wit Ale WLP400', yeast_type: 'Belgian Ale', attenuation: 76)
Yeast.create(name:'Trappist Ale WLP500', yeast_type: 'Belgian Ale', attenuation: 77.5)
Yeast.create(name:'Trappist  Gravity WY3787', yeast_type: 'Belgian Ale', attenuation: 76)
Yeast.create(name:'Belgian Strong Ale WLP545', yeast_type: 'Belgian Ale', attenuation: 81.5)
Yeast.create(name:'Trappist Blend WY3789', yeast_type: 'Belgian Ale', attenuation: 77)
Yeast.create(name:'Belgian Schelde WY3655', yeast_type: 'Belgian Ale', attenuation: 75)
Yeast.create(name:'Canadian/Belgian Ale WY3864', yeast_type: 'Belgian Ale', attenuation: 77)


#Sour
Yeast.create(name:'Berliner Blend GB122', yeast_type: 'Sour', attenuation: 89)
Yeast.create(name:'Farmhouse Sour GB121', yeast_type: 'Sour', attenuation: 89)
Yeast.create(name:'Fast Souring Lacto GB110', yeast_type: 'Sour', attenuation: 40)
Yeast.create(name:'Saison Sour GB124 Ale', yeast_type: 'Sour', attenuation: 78)
Yeast.create(name:'Sour Plum Belgian GB123', yeast_type: 'Sour', attenuation: 77)
Yeast.create(name:'Sweet Flemish Brett GB144', yeast_type: 'Sour', attenuation: 83)
Yeast.create(name:'Belgian Lambic Blend WY3278', yeast_type: 'Sour', attenuation: 75)
Yeast.create(name:'Lactobacillus WY5335', yeast_type: 'Sour', attenuation: 75)
Yeast.create(name:'Pediococcus WY5733', yeast_type: 'Sour', attenuation: 75)
Yeast.create(name:'Berliner Weisse Blend WLP630', yeast_type: 'Sour', attenuation: 76.5)
Yeast.create(name:'Bier de Garde WY3725', yeast_type: 'Sour', attenuation: 76)
Yeast.create(name:'Flanders Golden Ale WY3739', yeast_type: 'Sour', attenuation: 76)
Yeast.create(name:'Belgian Sour Mix WLP655', yeast_type: 'Sour', attenuation: 75)
Yeast.create(name:'Brettanomyces Bruxellensis WLP650', yeast_type: 'Sour', attenuation: 78)
Yeast.create(name:'Brettanomyces Bruxellensis Trois WLP644', yeast_type: 'Sour', attenuation: 85)
Yeast.create(name:'Brettanomyces Lambicus WLP653', yeast_type: 'Sour', attenuation: 78)
Yeast.create(name:'Flemish Ale Blend WLP665', yeast_type: 'Sour', attenuation: 83)
Yeast.create(name:'Berliner Weisse Blend WY3191', yeast_type: 'Sour', attenuation: 75)
Yeast.create(name:'Lactobacillus Brevis WLP672', yeast_type: 'Sour', attenuation: 80)
Yeast.create(name:'Brettanomyces bruxellensis WY5112', yeast_type: 'Sour', attenuation: 90)
Yeast.create(name:'Brettanomyces lambicus WY5526', yeast_type: 'Sour', attenuation: 90)

